---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Create nginx log directory
  file:
    path: /var/log/nginx
    state: directory
    mode: '0755'
    owner: www-data
    group: www-data

- name: Create web root directory
  file:
    path: "{{ web_root }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Remove default nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Configure Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'
    validate: 'nginx -t -c %s'
  notify: restart nginx

- name: Create virtual host configuration
  template:
    src: vhost.conf.j2
    dest: /etc/nginx/sites-available/default
    mode: '0644'
  notify: restart nginx

- name: Enable virtual host
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: restart nginx
